apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-db-volume
  labels:
    type: local
    app: user-db
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pv-data/dbuser
