apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-volume-claim
  labels:
    app: user-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
