apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
  labels:
    app: user-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: userdatabase
          - name: POSTGRES_USER
            value: userservice
          - name: POSTGRES_PASSWORD
            value: test
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: user-db-volume
      volumes:
        - name: user-db-volume
          persistentVolumeClaim:
            claimName: user-db-volume-claim    
